language: go

services:
  - postgresql

sudo: false

os:
  - linux

dist: xenial

before_script:
  - psql -c "create user buffalo_spelunking with password 'devpassword' superuser;" -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - go get -u -v github.com/gobuffalo/buffalo/buffalo
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.34.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 10
  - npm install

go:
  - "1.11.x"

go_import_path: github.com/JDWardle/buffalo_spelunking

script:
  - GO111MODULE=on buffalo build
  - GO111MODULE=on buffalo test
