language: go

services:
  - postgresql

sudo: false

os:
  - linux

dist: xenial

before_script:
  - psql -c 'create database buffalo_spelunking_test;' -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - go get -u -v github.com/gobuffalo/buffalo/buffalo

go:
  - "1.11.x"

go_import_path: github.com/JDWardle/buffalo_spelunking

script:
  - GO111MODULE=on buffalo build
  - GO111MODULE=on buffalo test
